<button type="button"
        data-role="proceed-to-checkout"
        title="<?php /* @escapeNotVerified */ echo __('Custom Checkout Method') ?>"
        data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?php /* @escapeNotVerified */ echo $block->getCheckoutUrl(); ?>"}}'
        class="action primary checkout">
    <span><?php /* @escapeNotVerified */ echo __('Custom Checkout Method') ?></span>
</button>

